name: Deploy Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_PROD_IP }}
          username: ${{ secrets.DEPLOY_SERVER_PROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:~/.nvm/versions/node/v21.4.0/bin
            cd ~/sites/bigspring-light-nextjs
            git pull origin main
            yarn install
            yarn build
            pm2 restart ismoildev-bigspring
            