name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_PROD_IP }}
          username: ${{ secrets.DEPLOY_SERVER_PROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/sites/bigspring-light-nextjs
            git pull origin main
            yarn install
            yarn build
            pm2 restart ismoildev-bigspring

      - name: Clean up
        if: always()
        run: npm uninstall -g yarn
